#!/usr/bin/env bash

clear


function one_fn {
	echo "one_fn function content:" "$@"
}

function two_fn {
	echo "two_fn function content:" "$@"
}

source "$DOROTHY/user/sources/_doc_helper.bash"
doc_helper
