#!/usr/bin/env bash

function reveal_() (
  source "$DOROTHY/sources/bash.bash"

  # reveal as much info about a specific command as possible.
  # ow

  # TODO: if the file is located in `commands.aliases` then
  # also print the description of the file!!
  # or even cat/bat the contents.

  echo "== REVEAL ============================================="
  for cmd in "$@"; do
    echo "Name: $cmd"
    echo "Which: $(which "$cmd")"
    echo-style --dim "$(which -a "$cmd")"
    echo-style "type: $(type "$cmd")"
    echo-style "type -p: $(type -p "$cmd")"
    echo "---------------------------------"
  done
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
  reveal_ "$@"
fi
