#!/usr/bin/env bash

function reveal_() (
	source "$DOROTHY/sources/bash.bash"

  echo "== REVEAL ============================================="
  for cmd in "$@"; do
    echo "name: $cmd"
    which "$cmd"
    type "$cmd"
  done
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	reveal_ "$@"
fi

