#!/usr/bin/env bash

clear

source "$DOROTHY/user/sources/_doc_helper.bash"

function one_fn {
    echo "one_fn function content:" "$@"
}

function two_fn {
    echo "two_fn function content:" "$@"
}

# data="$(get-definitions | prepare_data)"
# get-definitions | doc_helper
doc_helper < <(get-definitions)

# source "$DOROTHY/user/sources/_choose.bash"
# test_run_choose_from_script
