#!/usr/bin/env bash
# NAME: vl
# -------------------------------------------------------
# DESCRIPTION:
#  "CC=gcc-12 nvim"
# -------------------------------------------------------
$GHQ_ROOT/github.com/neovim/neovim/build/bin/nvim "$@"
