#!/usr/bin/env bash
# NAME: vv
# -------------------------------------------------------
# DESCRIPTION:
#  forked build
# -------------------------------------------------------
~/code/repos/github.com/neovim/neovim/build/bin/nvim "$@"
