#!/usr/bin/env bash
# NAME: dte
# -------------------------------------------------------
# DESCRIPTION:
# 
# -------------------------------------------------------
cd "$XDG_CONFIG_HOME/dorothy" && ${VISUAL:-${EDITOR:-vim}} . "$@"
