#!/usr/bin/env bash
# NAME: fz
# -------------------------------------------------------
# DESCRIPTION:
# # fh [FUZZY PATTERN] - Search in command histor
# -------------------------------------------------------
# ARGS: '$2'
print -z $( ( [ -n "$ZSH_NAME" ] && fc -l 1 || history ) | fzf +s --tac | sed 's/ *[0-9]* *//')
