#!/usr/bin/env bash
# NAME: gbrkout
# -------------------------------------------------------
# DESCRIPTION:
# 
# -------------------------------------------------------
git-subdir-make-into-module "$@"
