#!/usr/bin/env bash
# NAME: gcbn
# -------------------------------------------------------
# DESCRIPTION:
# 
# -------------------------------------------------------
git-get-checked-out-branch-name "$@"
