#!/usr/bin/env bash
# NAME: gcreb
# -------------------------------------------------------
# DESCRIPTION:
# 
# -------------------------------------------------------
git add --all && git commit -m 'REBASE ME!!!' "$@"
