#!/usr/bin/env bash
# NAME: ghprdev
# -------------------------------------------------------
# DESCRIPTION:
# 
# -------------------------------------------------------
gh pr create --base develop "$@"
