#!/usr/bin/env bash
# NAME: ghrc
# -------------------------------------------------------
# DESCRIPTION:
# # create public git rep
# -------------------------------------------------------
# ARGS: ''
gh repo create $1 --public
