#!/usr/bin/env bash
# NAME: netws
# -------------------------------------------------------
# DESCRIPTION:
#  <SSID_OF_NETWORK> <PASSWORD>
# -------------------------------------------------------
networksetup -setairportnetwork en0 "$@"
