#!/usr/bin/env bash
# NAME: svp
# -------------------------------------------------------
# DESCRIPTION:
# 
# -------------------------------------------------------
git add --all && git commit -m 'save' && git push "$@"
