#!/usr/bin/env bash
# NAME: tfl
# -------------------------------------------------------
# DESCRIPTION:
# 
# -------------------------------------------------------
teensy_loader_cli -mmcu=atmega32u4 -w ergodox_ez_molleweide.hex "$@"
