#!/usr/bin/env bash
# NAME: tns
# -------------------------------------------------------
# DESCRIPTION:
# # [SESSION_NAME | FUZZY PATTERN] - create new tmux session, or switch to existing one.
# Running `tm` will let you fuzzy-find a session mame
# Passing an argument to `ftm` will switch to that session if it exists or create it otherwis
# -------------------------------------------------------
# ARGS: '$1'
[[ -n "$TMUX" ]] && change="switch-client" || change="attach-session";
if [ $1 ]; then
    tmux $change -t "$1" 2> /dev/null || ( tmux new-session -d -s $1 && tmux $change -t "$1" );
    return;
fi;
session=$(tmux list-sessions -F "#{session_name}" 2> /dev/null | fzf --exit-0) && tmux $change -t "$session" || echo "No sessions found."
