[Keybindings]
  FocusGuildsList = "Alt+Rune[g]"
  FocusChannelsTreeView = "Alt+Rune[t]"
  FocusMessagesTextView = "Alt+Rune[m]"
  FocusMessageInputField = "Alt+Rune[i]"
  FocusMessageActionsList = "Alt+Rune[a]"
  SelectPreviousMessage = "Up"
  SelectNextMessage = "Down"
  SelectFirstMessage = "Home"
  SelectLastMessage = "End"

[General]
  UserAgent = "Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"
  FetchMessagesLimit = 50
  Mouse = true
  Notifications = true
  Timestamps = false
